### ISSUE TITLE
hello,I try to run your bot,but it can't answer me,don't know where wrong?

### ISSUE THREAD

**Issue by yhf2lj** [illvart/tg-serverless#1]
it run  success,but don't work in my bot

**Comment by yhf2lj** [comment]
when I type start or help in my tg , I can't receive the answer

**Comment by illvart** [comment]
> when I type start or help in my tg , I can't receive the answer



> when I type start or help in my tg , I can't receive the answer

I'm so sorry, for this time the bot not running because vercel have some bug. See [this bugs](https://github.com/illvart/tg-serverless#bugs) section.
